Reduce the image size of nodejs docker formula
ZupIT/ritchie-formulas pull request #167
Opened 2020-09-02 00:36 UTC by fabiocavalcantezup

**- What I did**
Reduced the size of final formula image (nodejs) from 967mb to 43.8mb. This also reduced the first time run of the formula from minutes to seconds.

Added obj/Debug and bin/Debug (from csharp template) to .gitignore. They kept being added when Omnisharp is running trying to background compile any .net code that is on vscode working directory.

**- How I did it**
Switch base image of NodeJS template from [cimg/node:14](https://hub.docker.com/r/cimg/node) to [alpine:3.12](https://hub.docker.com/_/alpine).
Also change the order of Docker commands to generate less layers reducing even more the size of image.

**- How to verify it**
Run docker build -t image_name . from the nodejs template folder

**- Description for the changelog**
- Reduced the final image size of nodejs template to less than 50mb

**- A picture of a cute animal (not mandatory but encouraged)**
Since it's encouraged, here it is:

![pork](https://static.boredpanda.com/blog/wp-content/uuuploads/cute-baby-animals/cute-baby-animals-10.jpg)

2020-09-03 17:22 UTC, henriquemoraeszup approved these changes
Fabião! Thanks for your contribution, the new image runs perfectly. Indeed we were facing long docker build times, thanks for taking action on it! We might be using this as a reference for the other templates as well. Also I did not know we could remove intermediate containers by reducing instructions this way, nice 👍 

<img width="879" alt="Screen Shot 2020-09-03 at 14 18 59" src="https://user-images.githubusercontent.com/68074718/92146740-86ef8700-edf0-11ea-9e80-b6a62e7a1be6.png">

2020-09-03 18:31 UTC, viniciussousazup commented on .gitignore
> +**/csharp/bin/**
Thanks for your contribution, could you change /templates/create_formula/root/.gitignore as well, since this file is copy when the user run `rit create formula` in a workspace that has no formula.

2020-09-04 12:13 UTC, fabianofernandeszup requested changes

2020-09-04 12:13 UTC, fabianofernandeszup commented on templates/create_formula/languages/node/Dockerfile
> +FROM alpine:3.12
Fabio, thanks for the contribution. The size of the docker images is really bothering us. But the problem is a little bigger. In the config.json file there is an attribute called dockerImageBuilder, and it has the image that will be used to build the formula. This dockerfile image is used only to run the formula. So if we have two different images, in the end it is still necessary to download both. But if we have the same image for build and execution, it will be just a download, because at the time of execution the build has already downloaded it.
So we need to find a more complete solution for these scenarios. If you have any suggestions we would be grateful.

2020-09-08 16:02 UTC, fabiocavalcantezup commented on .gitignore
> +**/csharp/bin/**
Will do it, sorry for the delay... I was kind busy last week.

2020-09-08 16:03 UTC, fabiocavalcantezup commented on templates/create_formula/languages/node/Dockerfile
> +FROM alpine:3.12
Fabiano, i perfectly understand. What do you think if i create a image and push to docker hub to be used at both stages instead?

2020-09-08 16:52 UTC, viniciussousazup commented on templates/create_formula/languages/node/Dockerfile
> +FROM alpine:3.12
we use the dockerImageBuilder only to run the makefile, maybe you can search or create a lighter docker image that can run the makefile

2020-09-08 17:13 UTC, fabiocavalcantezup commented on templates/create_formula/languages/node/Dockerfile
> +FROM alpine:3.12
Will work on it... Thanks for the tip.

2020-09-09 14:29 UTC, fabiocavalcantezup commented on templates/create_formula/languages/node/Dockerfile
> +FROM alpine:3.12
I have created a very simple (VERY) to run the makefile. Still didn't solve the problem of having two images... I have some ideas but will require some change at CLI, which at this moment i do not have many time (and knowledge, i admit) to make it.

With the changes added, it will still need double downloads, but one will be 5,8MB and another one still 43mb.

2020-09-09 18:31 UTC, fabianofernandeszup requested changes

2020-09-09 18:31 UTC, fabianofernandeszup commented on templates/create_formula/languages/node/config.json
> +  "dockerImageBuilder": "kobuti/make-runner:1.0.0",
This image also needs to have the node and npm installed, as it will be used in the formula build process when it is run with docker.
To be able to test this flow, delete the /bin folder from the formula and call its execution with the --docker parameter. So the build will be done in the docker. If the bin folder is not removed, rit only runs on the docker, as it understands that the build already exists.
Example of the location of the bin folder: ~ / .rit / repos / NAME_REPO / group / verb / noun / bin

2020-09-10 20:24 UTC, viniciussousazup commented on templates/create_formula/languages/node/config.json
> +  "dockerImageBuilder": "kobuti/make-runner:1.0.0",
An error happens:
- Copy your template version to ~/.rit/repos/commons/template
- Create a new formula with node template
- Run with --docker

![image](https://user-images.githubusercontent.com/42281176/92799812-7b6d0480-f38a-11ea-9ce9-d8283ce62532.png)

2020-09-10 20:35 UTC, viniciussousazup commented on templates/create_formula/languages/node/config.json
> +  "dockerImageBuilder": "kobuti/make-runner:1.0.0",
Maybe if you show the Dockerfile that you use to create kobuti/make-runner:1.0.0 we can help you.

2020-09-10 20:49 UTC, fabiocavalcantezup commented on templates/create_formula/languages/node/config.json
> +  "dockerImageBuilder": "kobuti/make-runner:1.0.0",
Indeed i made a mistake, i fixed with a 1.1.0 version of the image

@viniciussousazup https://github.com/fabiocavalcantezup/utils/blob/master/Dockerfile, here it is.

2020-09-10 20:59 UTC, viniciussousazup approved these changes
![image](https://user-images.githubusercontent.com/42281176/92805208-4c0cc680-f38f-11ea-9235-c4546013b960.png)

Good Job :rocket::rocket::rocket:

2020-10-16 15:04 UTC, fabianofernandeszup commented
First thanks for the contribution.
We are bored with the need to reduce the images and for that we are reviewing all the images used and creating an official repo of the ritchie with these documented images.
So for this reason we are going to close this PR because it will already be included in this general review.
But we appreciate your contribution and we hope you continue to help us.

2020-10-16 15:04 UTC, closed without merging