Feature/language typescript
ZupIT/ritchie-formulas pull request #243
Opened 2020-09-25 19:33 UTC by brunonmelo

# Pull Request

## What I did
I created a new language template for Typespcript.

## How I did it
I used the allready existing Node template as base for create this new one.

## How to verify it
When you create a new formula, Typescript will be listed on the languages as an option.

## What kind of change does this PR make

- [ ] Major
- [x] Minor
- [ ] Patch

## Description for the changelog
Adding Typescript as a new language template option.

2020-09-29 19:03 UTC, GuillaumeFalourd requested changes

2020-09-29 19:03 UTC, GuillaumeFalourd commented on templates/create_formula/languages/typescript/config.json
> +}
Hi @brunonmelo 
We opened some issues (like this one: https://github.com/ZupIT/ritchie-formulas/issues/157) to update the hello world templates in many languages to match the rit demo hello-world formula in GO : https://github.com/ZupIT/ritchie-formulas/tree/master/demo/hello-world with the same inputs and the same display.

Would it be possible to create this TYPESCRIPT template already following this new structure ? Otherwise we'll need to open another ISSUE to update this template.

2020-09-29 19:03 UTC, GuillaumeFalourd commented on templates/create_formula/languages/typescript/src/formula/formula.ts
> +export default formula
This class will also be affected by the change I suggested for the config.json file.

2020-09-29 19:03 UTC, GuillaumeFalourd commented on templates/create_formula/languages/typescript/src/index.ts
> +run(input1, input2, input3)
This class will also be affected by the change I suggested for the config.json file.

2020-09-29 20:27 UTC, GuillaumeFalourd approved these changes

2020-09-29 21:25 UTC, brunonmelo commented on templates/create_formula/languages/typescript/config.json
> +}
Not a problem at all.
I've already made some adjustment to adequate the template to this new model.

2020-09-29 21:28 UTC, brunonmelo commented
I'm think this MR could benefits from this change too #167 .
What do you think @GuillaumeFalourd ?

2020-10-01 12:31 UTC, fabianofernandeszup commented on templates/create_formula/languages/typescript/src/index.ts
> +const iFormula: IFormula = {
First, thanks for the contribution.
Formula templates are usually made in the simplest way for easy understanding by new users.
In this case I think that an interface would not be necessary to pass the data to the run function, what do you think?

2020-10-01 12:33 UTC, fabianofernandeszup commented on templates/create_formula/languages/typescript/src/index.ts
> +const iFormula: IFormula = {
One more detail. This PR does not enter the hacktoberfest because it was opened before. If you want, I think you can close it and open it again, so you can participate in the event.

2020-10-01 21:10 UTC, brunonmelo commented on templates/create_formula/languages/typescript/src/index.ts
> +const iFormula: IFormula = {
Hey @fabianofernandeszup, thanks.

And you are right. Normally, this interface would not be need for this template to work, but I wanted to demonstrate a small advantage of what you can do with Typescript over the vanila Javascript.

But I can remove, it's not a problem at all.

2020-10-01 21:14 UTC, brunonmelo commented on templates/create_formula/languages/typescript/src/index.ts
> +const iFormula: IFormula = {
And I thought about close and open this MR for the hacktoberfest, perhaps I do this. 😁️

2020-10-01 21:47 UTC, GuillaumeFalourd commented
> I'm think this MR could benefits from this change too #167 .
> What do you think @GuillaumeFalourd ?

As you wish, you can split it in 2 contributions as well to be count as 2 MR for the Hacktoberfest event.

Moreover, if you want this MR to be valid for the Hacktoberfest event, you'll have to close it and open it again (no problem with us).

2020-10-02 11:33 UTC, closed without merging

2020-10-02 12:02 UTC, brunonmelo commented
I opened a new pull request for Hacktoberfest:
#254