[Improvement] - Windows support to templates
ZupIT/ritchie-formulas pull request #247
Opened 2020-09-30 18:09 UTC by JoaoDanielRufino

Signed-off-by: JoaoDanielRufino <joaodaniel0405@gmail.com>

# Pull Request

## What I did
Added the possibility to create formulas in batch

## How I did it
Adding build.bat and formula.bat to shell template

## How to verify it
`rit create formula` and select the option shell-bat

## What kind of change does this PR make

- [ ] Major
- [ ] Minor
- [ ] Patch

## Description for the changelog
Added the possibility to create formulas in batch

2020-10-05 21:20 UTC, maurineimirandazup submitted a review, later dismissed

2020-10-07 14:48 UTC, fabianofernandeszup requested changes

2020-10-07 14:48 UTC, fabianofernandeszup commented on templates/create_formula/languages/shell-bat/src/windows/formula/formula.bat
> +  echo You receive %SAMPLE_BOOL% in boolean.
Update this output according to the formula in shell.

2020-10-08 17:54 UTC, fabianofernandeszup approved these changes

2020-10-08 17:54 UTC, merged