Update Node.js template
ZupIT/ritchie-formulas pull request #262
Opened 2020-10-04 08:40 UTC by prateek1998

# Pull Request

## What I did
Update the nodejs template  #257 

## How I did it
I updated three files: config.json, index.js, formula.js.

## How to verify it
check it by running in local.

## What kind of change does this PR make

- [x] Major
- [ ] Minor
- [ ] Patch

## Description for the changelog
1. added a new package which is necessary.
2. added the path which is required.
3. reformat the template.

2020-10-04 08:42 UTC, prateek1998 commented
please review and merge this pr.
thanks

2020-10-05 13:39 UTC, GuillaumeFalourd commented
Hi @prateek1998 , thank you for contributing 👍 
|

You need to complete 2 more steps: 
- The DCO (to sign-off your PR)
- The conflicting files (`templates/create_formula/languages/node/config.json`)

I loved the way to updated the index.js class 😄

2020-10-05 14:18 UTC, GuillaumeFalourd requested changes

2020-10-05 14:18 UTC, GuillaumeFalourd commented on templates/create_formula/languages/node/src/index.js
> +const INPUT4 = process.env.INPUT_PASSWORD||config_data.inputs[3].name
This `config_data.inputs[x]` parameter seems interesting, but after discussing with the team, we think it might bring an extra complexity, as you will have to put the position of the array to get the input, and this will create a mandatory order, so even if it works, there would be an unforeseen behavior.

As it's a template that all users will manipulate, we want the structure to be as simple as possible for people to understand the fastest  way possible how to implement their formula.

Makes sense @prateek1998 ?

2020-10-05 14:26 UTC, prateek1998 commented on templates/create_formula/languages/node/src/index.js
> +const INPUT4 = process.env.INPUT_PASSWORD||config_data.inputs[3].name
okay, I understand so can I remove it?

2020-10-05 14:33 UTC, GuillaumeFalourd commented on templates/create_formula/languages/node/src/index.js
> +const INPUT4 = process.env.INPUT_PASSWORD||config_data.inputs[3].name
Yes, we could try this implementation in a formula to get a use-cases with it.
But let's keep it simple in the template for now:

```
const INPUT1 = process.env.INPUT_TEXT
const INPUT2 = process.env.INPUT_BOOLEAN
const INPUT3 = process.env.INPUT_LIST
const INPUT4 = process.env.INPUT_PASSWORD
```

2020-10-05 14:35 UTC, prateek1998 commented on templates/create_formula/languages/node/src/index.js
> +const INPUT4 = process.env.INPUT_PASSWORD||config_data.inputs[3].name
Thanks @GuillaumeFalourd

2020-10-05 14:51 UTC, GuillaumeFalourd commented on templates/create_formula/languages/node/src/index.js
> +const INPUT4 = process.env.INPUT_PASSWORD||config_data.inputs[3].name
The inputs on the`config.json`file should be exactly the same than here : https://github.com/ZupIT/ritchie-formulas-demo/blob/master/demo/hello-world/config.json

2020-10-05 15:01 UTC, GuillaumeFalourd commented
You need to complete 2 more steps:
- The DCO (to sign-off your PR)
- The conflicting files (templates/create_formula/languages/node/config.json) --> just fetching the upstream and merging the upstream/master on your branch.

2020-10-05 15:02 UTC, prateek1998 commented on templates/create_formula/languages/node/src/index.js
> +const INPUT4 = process.env.INPUT_PASSWORD||config_data.inputs[3].name
I have updated the code, please review.

2020-10-05 15:04 UTC, GuillaumeFalourd commented on templates/create_formula/languages/node/src/index.js
> +config_data = require(path.resolve('../config.json'));
Now that you revert your implementation.

You can keep the `const run = require("./formula/formula")` line.

And remove the following block
```
var path = require('path'),
run = require("./formula/formula"),
config_data = require(path.resolve('../config.json'));
```

2020-10-05 15:34 UTC, prateek1998 commented
please help the reviewer, I do not understand what is the issue in  merging the pr.

2020-10-05 16:58 UTC, GuillaumeFalourd approved these changes

2020-10-05 16:59 UTC, GuillaumeFalourd commented
> please help the reviewer, I do not understand what is the issue in merging the pr.

You resolved the conflict, that part is ok now and I approved your PR.
However, you still have to sign-off the DCO (Developer Certificate of Origin) to allow us to merge your contribution.

![Screen Shot 2020-10-05 at 13 58 16](https://user-images.githubusercontent.com/22433243/95109325-d76d4380-0712-11eb-8944-45e91576b1fb.png)

2020-10-06 15:13 UTC, prateek1998 commented
Can you help me, I am not able to resolve the issue.

2020-10-06 16:00 UTC, GuillaumeFalourd commented
> Can you help me, I am not able to resolve the issue. We can connect using the meet app or any other platform.

The implementation you submitted for this ISSUE is ok.

We just have a few steps that validate the PR before being able to merge it.

As you can see below this comment:
- [ ] DCO --> Details
- [x] ci/circleci: pre-commit — Your tests passed on CircleCI!
- [x] ci/circleci: unit-test — Your tests passed on CircleCI!

You just need to Sign-off your PR because it's a mandatory step for us to approve the request.

Click in `Details` next to DCO and you'll see an explanation about how to sign-off 👍

2020-10-06 16:07 UTC, prateek1998 commented
![image](https://user-images.githubusercontent.com/37973089/95227716-11763c80-081c-11eb-804f-03d99f83b1d4.png)
I am getting this error

2020-10-06 17:23 UTC, GuillaumeFalourd commented
Hmm, try following this step by step then : https://probot.github.io/apps/dco/

2020-10-07 18:32 UTC, prateek1998 commented
Hii Reviewer #267, I have created a new pull request with DCO attach please merge the pr.
thank you

2020-10-07 18:55 UTC, closed without merging