[Feature] Formulas for http performance test: http-load & http-config
ZupIT/ritchie-formulas pull request #282
Opened 2020-10-16 12:41 UTC by douglasvinter

# Pull Request

## What I did
- Created a new command super set named `http` which is suppose to provide http testing & development tools
- Created the very first http helper command named `rit http perform load-test`, which is an simple HTTP performance testing tool
- Created the second http command, named `rit http generate http-config`, which generates the target http host into a json file on users `~/.rit` folder

## How I did it
- Used some HTTP tools as inspiration (go lang vegeta, JMeter, Gatlin) to create the very first, simple and light weight ritchie's performance tool
- Used go routines without a mutex to increment correlation-ID and sequency-ID on HTTP Headers (That might requires security off in some target applications)
- The concurrency model (a.k.a threading spawn) is based on Brian Goetz thread pool formula

## How to verify it

- build the formula, generate the default config file using the command `rit http perform load-test`, edit the created file (if you want to) and then run the command `rit http perform load-test`
- the formula will ask for the test duration (in seconds) and the desired max threads (go routines) to be used, if you pass the value 0, the defaultMaxWorkers value will be used
- Dots ("..") will be printed while running as a feedback that its running, and will notify you when its done with the results file full path for you to copy and paste, which is by default named: `ritman-test-result-<timestamp>.json`

## What kind of change does this PR make

- [ ] Major
- [X] Minor
- [ ] Patch

## Description for the changelog
- Added a formula for HTTP performance test
- Added a formula to generate the base configuration template

2020-10-16 13:01 UTC, GuillaumeFalourd requested changes
Just a couple of comments regarding the README files, the rest looks good to me 👍🏼

2020-10-16 13:01 UTC, GuillaumeFalourd commented on http/generate/http-config/README.md
> +4. The "body" field supports any valid JSON format, so you can fullfill with your disired test content.
Great description of the formula 👍🏼  
Could you just update it to look more like the default README we recommend to use please @douglasvinter ?

Example: https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world

2020-10-16 13:01 UTC, GuillaumeFalourd commented on http/perform/load-test/README.md
> +    - ms - stands for milliseconds
Great description of the formula 👍🏼  
Could you just update it to look more like the default README we recommend to use please @douglasvinter ?

Example: https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world

2020-10-16 16:32 UTC, douglasvinter commented on http/generate/http-config/README.md
> +4. The "body" field supports any valid JSON format, so you can fullfill with your disired test content.
Done

2020-10-16 17:55 UTC, GuillaumeFalourd approved these changes

2020-10-16 17:56 UTC, GuillaumeFalourd commented
LGTM @douglasvinter 🚀 
Just sign-off the DCO please, for the PR to be approved 👍🏼

2020-10-16 22:36 UTC, douglasvinter commented
DCO done

2020-10-19 12:03 UTC, GuillaumeFalourd approved these changes

2020-10-19 12:04 UTC, merged

2020-10-19 12:04 UTC, GuillaumeFalourd commented
Thank you for contributing @douglasvinter , with one more accepted PR you'll be able to participate the [ZupIT challenge for the hacktoberfest](https://insights.zup.com.br/hacktoberfest)! 🚀