Update the README KAFKA create topic for issue #221.
ZupIT/ritchie-formulas pull request #311
Opened 2020-10-31 22:06 UTC by afonsoaugusto

Signed-off-by: Afonso Rodrigues <afonso.rodrigues@maxmilhas.com.br>

# Pull Request

## What I did
Change README with execution the command `rit create topic`

## How I did it
Change README

## How to verify it
Check this PR
![Alt Text](https://media.giphy.com/media/o8MA12cSey3NSnp6pq/source.gif)

## What kind of change does this PR make

- [ ] Major
- [ ] Minor
- [X] Patch

## Description for the changelog

 issue #221

2020-10-31 22:42 UTC, fabianofernandeszup approved these changes

2020-10-31 22:44 UTC, fabianofernandeszup requested changes
First of all, thanks for the contribution.
There was a conflict in your PR. I already did the initial analysis and everything seems fine to me.
As soon as I resolve the conflict, I can accept it.

2020-11-01 00:44 UTC, GuillaumeFalourd commented
Hasn't this Issue (update the rit kafka create topic readme) already been resolved by the #309 PR ?

2020-11-02 00:27 UTC, fabianofernandeszup submitted a review, later dismissed

2020-11-03 14:28 UTC, afonsoaugusto commented
Hi @fabianofernandeszup , conflicts is solved.

2020-11-03 14:48 UTC, GuillaumeFalourd requested changes

2020-11-03 14:48 UTC, GuillaumeFalourd commented on kafka/create/topic/README.md
>  ## Premisse
Hi @afonsoaugusto , there are 2 Premisse topic, we could remove one.

2020-11-03 14:48 UTC, GuillaumeFalourd commented on kafka/create/topic/README.md
> +This create kafka topic command allows the user to delete a bucket in AWS S3
I think there is a problem with the description talking about AWS S3 bucket here.
You could maybe re-use the command above :

```
This formula create a topic on the inform kafka URL.
You can test it using docker with the `rit docker generate compose` formula.
```

2020-11-03 18:59 UTC, afonsoaugusto commented on kafka/create/topic/README.md
> +This create kafka topic command allows the user to delete a bucket in AWS S3
Hi @GuillaumeFalourd , My apologies the bad description in my commit. I kept a template with addiction the another implementation. I will update with this description.

2020-11-03 19:01 UTC, afonsoaugusto reviewed
Update the README.md with orientations

2020-11-03 20:16 UTC, GuillaumeFalourd approved these changes

2020-11-03 20:17 UTC, GuillaumeFalourd commented
You just need to sign-off the DCO @afonsoaugusto and we'll merge your contribution 😄 
Thanks for the update 👍🏼

2020-11-09 12:57 UTC, afonsoaugusto commented
@GuillaumeFalourd ,
How to sign-off the commit after change?

2020-11-09 15:16 UTC, GuillaumeFalourd approved these changes

2020-11-09 15:16 UTC, merged