Add formula
ZupIT/ritchie-formulas pull request #364
Opened 2021-04-14 17:45 UTC by antoniofilhozup

# Pull Request

## What I did
A new formula to delete an item from Amazon SQS.

## How I did it

Using AWS CLI

## How to verify it
Run `rit aws delete sqs-item`

## What kind of change does this PR make

- [ ] Major
- [ x ] Minor
- [ ] Patch

## Description for the changelog

Add `rit aws delete sqs-item` formula

2021-04-14 18:46 UTC, GuillaumeFalourd requested changes

2021-04-14 18:46 UTC, GuillaumeFalourd commented on aws/delete/sqs-item/README.md
> +# Ritchie Formula
This formula README file isn't following the new README pattern ([example](https://github.com/ZupIT/ritchie-formulas/blob/master/aws/add/terraform-eks/README.md)). Could you update it please? 👍🏼

2021-04-14 18:46 UTC, GuillaumeFalourd commented on aws/delete/sqs-item/Dockerfile
> +RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install
Question: I see you download the `.zip` file and unzip it to install aws.

I've seen other option online such as the following that looks easier and less verbose. Would it be an option to use something like this on the Dockerfile (with the rest of RIT configurations) ?

```FROM python:3-alpine

RUN pip3 --no-cache-dir install --upgrade awscli
```

2021-04-14 21:05 UTC, antoniofilhozup commented on aws/delete/sqs-item/README.md
> +# Ritchie Formula
done

2021-04-15 18:12 UTC, GuillaumeFalourd approved these changes
👍🏼

2021-04-15 18:15 UTC, merged